runtime: nodejs20

env_variables:
  NODE_ENV: production
  PORT: 8080
  RESEND_API_KEY: re_demo_key_for_development_only
  FROM_EMAIL: noreply@dev-splicer-463021-u3.uc.r.appspot.com
  GOOGLE_CLOUD_PROJECT: dev-splicer-463021-u3
  ALLOWED_ORIGINS: https://dev-splicer-463021-u3.web.app,https://dev-splicer-463021-u3.firebaseapp.com
  RATE_LIMIT_MAX: 100
  RATE_LIMIT_WINDOW: 900000
  JWT_SECRET: dev-super-secret-jwt-key-at-least-32-characters-long-for-production
  
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always

instance_class: F2
